# Azure DevOps pipeline template used to setup the Node project:
# 1. checkout code
# 2. setup correct node version
# 3. install node dependencies

parameters:
  # the branch, tag or commit to deploy
  - name: 'gitReference'
    type: string
    default: '$(Build.SourceVersion)'

steps:
  - checkout: self                    # self represents the repo where the initial Azure Pipelines YAML file was found
    displayName: 'Checkout'

  # This is needed because the pipeline may point to a different commit than expected
  # The common case is when the previous stage pushed another commit
  - ${{ if ne(parameters.gitReference, variables['Build.SourceVersion']) }}:
      - script: |
          git fetch && git checkout ${{ parameters.gitReference }}
        displayName: 'Checkout reference'

  - task: UseNode@1
    inputs:
      version: $(NODE_VERSION)
    displayName: 'Set up Node.js'

  - script: pwd && ls
    workingDirectory: pagopa-api-config-fe
    displayName: 'Current dir'

  - script: yarn install --frozen-lockfile --no-progress --non-interactive --network-concurrency 1
    workingDirectory: pagopa-api-config-fe
    displayName: 'Install node modules'
