import React from "react";


export default class MainContent extends React.Component {

    render(): React.ReactNode {
        return (
                <div>

                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque augue turpis, blandit sed ante ornare, tincidunt gravida nisl. Curabitur sed nibh augue. Praesent et libero arcu. Cras accumsan ipsum at elit imperdiet, id tristique ex vestibulum. Curabitur vel posuere ligula. In hac habitasse platea dictumst. Integer fringilla ipsum eget tellus viverra pellentesque. Duis id ante id dui venenatis ultricies. Nullam turpis purus, maximus vel volutpat non, luctus ac lacus. Morbi convallis libero velit, non finibus lectus facilisis vel.

                    Quisque elementum elit non libero luctus pulvinar. Pellentesque interdum sodales ex, in varius nunc blandit eget. In volutpat nisl et lobortis semper. Morbi vitae sapien eu ligula sagittis aliquet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Etiam at justo elit. Vestibulum tincidunt fringilla arcu vel auctor. Proin sit amet auctor urna, ac tempus tellus. Curabitur et magna cursus, lobortis diam sed, porta velit. In vestibulum sed lorem nec feugiat. Ut placerat, ligula in imperdiet faucibus, orci purus commodo tellus, vel lacinia leo nibh ac tortor.

                    Duis lacinia sagittis euismod. Nam cursus luctus odio sed auctor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec egestas hendrerit ex ut commodo. Nam semper, dui vitae rutrum tincidunt, enim nunc porttitor mauris, quis hendrerit urna massa sit amet nulla. In dignissim sed neque commodo pellentesque. Praesent elementum, lectus et porttitor interdum, nunc turpis ullamcorper purus, at auctor erat dui vitae libero. Vivamus interdum pulvinar efficitur.

                    Sed pellentesque at tortor eu euismod. Etiam hendrerit vel nulla non lacinia. Duis dignissim feugiat sapien ac commodo. Mauris a mollis quam, eget tincidunt leo. Sed lacinia consequat massa in cursus. Nunc imperdiet arcu eu nisl vehicula lobortis. Vestibulum ultricies euismod lorem, eleifend viverra diam egestas a. In pellentesque elit et nibh fermentum porta.

                    Integer lobortis est et turpis tempus gravida. Donec odio sem, tempus ac cursus a, condimentum quis urna. Cras scelerisque id elit eget fermentum. Aliquam vitae sagittis dolor. Donec justo lectus, bibendum id tellus vitae, facilisis elementum mi. Quisque sollicitudin mattis ante, nec ullamcorper quam maximus eu. Vestibulum sollicitudin, justo in porttitor condimentum, mauris sem blandit nulla, pretium luctus nisi risus at sapien. Curabitur at ex sit amet lectus accumsan maximus nec ac tellus. Nunc ante mauris, sagittis non consequat et, convallis vitae tellus.

                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque augue turpis, blandit sed ante ornare, tincidunt gravida nisl. Curabitur sed nibh augue. Praesent et libero arcu. Cras accumsan ipsum at elit imperdiet, id tristique ex vestibulum. Curabitur vel posuere ligula. In hac habitasse platea dictumst. Integer fringilla ipsum eget tellus viverra pellentesque. Duis id ante id dui venenatis ultricies. Nullam turpis purus, maximus vel volutpat non, luctus ac lacus. Morbi convallis libero velit, non finibus lectus facilisis vel.

                    Quisque elementum elit non libero luctus pulvinar. Pellentesque interdum sodales ex, in varius nunc blandit eget. In volutpat nisl et lobortis semper. Morbi vitae sapien eu ligula sagittis aliquet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Etiam at justo elit. Vestibulum tincidunt fringilla arcu vel auctor. Proin sit amet auctor urna, ac tempus tellus. Curabitur et magna cursus, lobortis diam sed, porta velit. In vestibulum sed lorem nec feugiat. Ut placerat, ligula in imperdiet faucibus, orci purus commodo tellus, vel lacinia leo nibh ac tortor.

                    Duis lacinia sagittis euismod. Nam cursus luctus odio sed auctor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec egestas hendrerit ex ut commodo. Nam semper, dui vitae rutrum tincidunt, enim nunc porttitor mauris, quis hendrerit urna massa sit amet nulla. In dignissim sed neque commodo pellentesque. Praesent elementum, lectus et porttitor interdum, nunc turpis ullamcorper purus, at auctor erat dui vitae libero. Vivamus interdum pulvinar efficitur.

                    Sed pellentesque at tortor eu euismod. Etiam hendrerit vel nulla non lacinia. Duis dignissim feugiat sapien ac commodo. Mauris a mollis quam, eget tincidunt leo. Sed lacinia consequat massa in cursus. Nunc imperdiet arcu eu nisl vehicula lobortis. Vestibulum ultricies euismod lorem, eleifend viverra diam egestas a. In pellentesque elit et nibh fermentum porta.

                    Integer lobortis est et turpis tempus gravida. Donec odio sem, tempus ac cursus a, condimentum quis urna. Cras scelerisque id elit eget fermentum. Aliquam vitae sagittis dolor. Donec justo lectus, bibendum id tellus vitae, facilisis elementum mi. Quisque sollicitudin mattis ante, nec ullamcorper quam maximus eu. Vestibulum sollicitudin, justo in porttitor condimentum, mauris sem blandit nulla, pretium luctus nisi risus at sapien. Curabitur at ex sit amet lectus accumsan maximus nec ac tellus. Nunc ante mauris, sagittis non consequat et, convallis vitae tellus.

                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque augue turpis, blandit sed ante ornare, tincidunt gravida nisl. Curabitur sed nibh augue. Praesent et libero arcu. Cras accumsan ipsum at elit imperdiet, id tristique ex vestibulum. Curabitur vel posuere ligula. In hac habitasse platea dictumst. Integer fringilla ipsum eget tellus viverra pellentesque. Duis id ante id dui venenatis ultricies. Nullam turpis purus, maximus vel volutpat non, luctus ac lacus. Morbi convallis libero velit, non finibus lectus facilisis vel.

                    Quisque elementum elit non libero luctus pulvinar. Pellentesque interdum sodales ex, in varius nunc blandit eget. In volutpat nisl et lobortis semper. Morbi vitae sapien eu ligula sagittis aliquet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Etiam at justo elit. Vestibulum tincidunt fringilla arcu vel auctor. Proin sit amet auctor urna, ac tempus tellus. Curabitur et magna cursus, lobortis diam sed, porta velit. In vestibulum sed lorem nec feugiat. Ut placerat, ligula in imperdiet faucibus, orci purus commodo tellus, vel lacinia leo nibh ac tortor.

                    Duis lacinia sagittis euismod. Nam cursus luctus odio sed auctor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec egestas hendrerit ex ut commodo. Nam semper, dui vitae rutrum tincidunt, enim nunc porttitor mauris, quis hendrerit urna massa sit amet nulla. In dignissim sed neque commodo pellentesque. Praesent elementum, lectus et porttitor interdum, nunc turpis ullamcorper purus, at auctor erat dui vitae libero. Vivamus interdum pulvinar efficitur.

                    Sed pellentesque at tortor eu euismod. Etiam hendrerit vel nulla non lacinia. Duis dignissim feugiat sapien ac commodo. Mauris a mollis quam, eget tincidunt leo. Sed lacinia consequat massa in cursus. Nunc imperdiet arcu eu nisl vehicula lobortis. Vestibulum ultricies euismod lorem, eleifend viverra diam egestas a. In pellentesque elit et nibh fermentum porta.

                    Integer lobortis est et turpis tempus gravida. Donec odio sem, tempus ac cursus a, condimentum quis urna. Cras scelerisque id elit eget fermentum. Aliquam vitae sagittis dolor. Donec justo lectus, bibendum id tellus vitae, facilisis elementum mi. Quisque sollicitudin mattis ante, nec ullamcorper quam maximus eu. Vestibulum sollicitudin, justo in porttitor condimentum, mauris sem blandit nulla, pretium luctus nisi risus at sapien. Curabitur at ex sit amet lectus accumsan maximus nec ac tellus. Nunc ante mauris, sagittis non consequat et, convallis vitae tellus.

                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque augue turpis, blandit sed ante ornare, tincidunt gravida nisl. Curabitur sed nibh augue. Praesent et libero arcu. Cras accumsan ipsum at elit imperdiet, id tristique ex vestibulum. Curabitur vel posuere ligula. In hac habitasse platea dictumst. Integer fringilla ipsum eget tellus viverra pellentesque. Duis id ante id dui venenatis ultricies. Nullam turpis purus, maximus vel volutpat non, luctus ac lacus. Morbi convallis libero velit, non finibus lectus facilisis vel.

                    Quisque elementum elit non libero luctus pulvinar. Pellentesque interdum sodales ex, in varius nunc blandit eget. In volutpat nisl et lobortis semper. Morbi vitae sapien eu ligula sagittis aliquet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Etiam at justo elit. Vestibulum tincidunt fringilla arcu vel auctor. Proin sit amet auctor urna, ac tempus tellus. Curabitur et magna cursus, lobortis diam sed, porta velit. In vestibulum sed lorem nec feugiat. Ut placerat, ligula in imperdiet faucibus, orci purus commodo tellus, vel lacinia leo nibh ac tortor.

                    Duis lacinia sagittis euismod. Nam cursus luctus odio sed auctor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec egestas hendrerit ex ut commodo. Nam semper, dui vitae rutrum tincidunt, enim nunc porttitor mauris, quis hendrerit urna massa sit amet nulla. In dignissim sed neque commodo pellentesque. Praesent elementum, lectus et porttitor interdum, nunc turpis ullamcorper purus, at auctor erat dui vitae libero. Vivamus interdum pulvinar efficitur.

                    Sed pellentesque at tortor eu euismod. Etiam hendrerit vel nulla non lacinia. Duis dignissim feugiat sapien ac commodo. Mauris a mollis quam, eget tincidunt leo. Sed lacinia consequat massa in cursus. Nunc imperdiet arcu eu nisl vehicula lobortis. Vestibulum ultricies euismod lorem, eleifend viverra diam egestas a. In pellentesque elit et nibh fermentum porta.

                    Integer lobortis est et turpis tempus gravida. Donec odio sem, tempus ac cursus a, condimentum quis urna. Cras scelerisque id elit eget fermentum. Aliquam vitae sagittis dolor. Donec justo lectus, bibendum id tellus vitae, facilisis elementum mi. Quisque sollicitudin mattis ante, nec ullamcorper quam maximus eu. Vestibulum sollicitudin, justo in porttitor condimentum, mauris sem blandit nulla, pretium luctus nisi risus at sapien. Curabitur at ex sit amet lectus accumsan maximus nec ac tellus. Nunc ante mauris, sagittis non consequat et, convallis vitae tellus.
                </div>
        );
    }
}
